language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-synth' ]; then cd .. && eval "mv $currentfolder generator-synth" && cd generator-synth; fi

